### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by arpia49**
Hello, I hope the format is fine.

Let me know if I need to correct something.

--Adal

### CODE REVIEW

**Comment by LynithDev** [comment]
Hi! Thanks for the translations however I think there is an issue. I don't think the Spanish code is `es_ES` as provided in line 14.

Could you double check if it works by following these instructions:
Pack the extension with `chmod u+x ./pack.sh && ./pack.sh` and then extract the zip and move the folder to `~/.local/share/gnome-shell/extensions/`

Reload / restart GNOME (Xorg: `ALT+F2`, type in `r`, Wayland: Log out and log in) and it should work if done correctly

**Comment by arpia49** [comment]
Thanks, I was under the impression that es_ES was the correct code (as the zh_CN). I'll check and keep you posted.

**Comment by arpia49** [comment]
I just had time to review and both `es` and `es_ES` works fine on my environment. My asumption is that `es` would work for all Spanish variants and `es_ES` would be speciffic for Spanish from Spain. Asumption based in... a gut feeling?

In any case, I've spoted a mistake on the charset while testing.

I've changed to `es` as I think my Spanish words should begeneric but in case someone (from Latin America?)  complains in the future, maybe it makes sense to recheck the locale for this.

**Comment by LynithDev** [comment]
Alright. Thanks for testing I appreciate it!

**Pull request merged**
