### PR TITLE
Change zh_cn -> zh_CN

### PR DESCRIPTION
**Pull request by xiaozhangup**
To be honest I don't really understand gnome's language file reading rules, I remember that when I translated some extensions before zh_cn could be read properly, but this one doesn't seem to work.
Can you check it again?

### CODE REVIEW

**Comment by LynithDev** [comment]
I'll check it locally this time. This is on me for not checking

**Comment by LynithDev** [comment]
Well I can't seem to load GNOME with the chinese language. Are you sure this works?

**Comment by xiaozhangup** [comment]
> Well I can't seem to load GNOME with the chinese language. Are you sure this works?

I will test now

**Comment by LynithDev** [comment]
You can pack the extension with the shell script and then move it to `~/.local/share/gnome-shell/extensions/`

Reload / restart GNOME and it should work if done correctly

**Comment by xiaozhangup** [comment]
> You can pack the extension with the shell script and then move it to `~/.local/share/gnome-shell/extensions/`
> 
> Reload / restart GNOME and it should work if done correctly

well,work fine for me
图片

**Comment by LynithDev** [comment]
Great! I'll update the extension in about an hour

**Pull request merged**
